name: Checkstyle

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - test

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install dependencies
      run: mvn install -DskipTests -Dcheckstyle.skip

    - name: List files
      run: ls -R

    - name: Run Checkstyle
      run: mvn checkstyle:check -Dcheckstyle.config.location=./checkstyle.xml
